royal_academy:
    resource: "@RoyalAcademyBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

royal_academy_examen:
        resource: "@RoyalAcademyBundle/Resources/config/routing/examen.php"
        prefix:   /examen