<?php

namespace RoyalAcademyBundle\Repository;

/**
 * examenrealizado_has_respuestaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class examenrealizado_has_respuestaRepository extends \Doctrine\ORM\EntityRepository
{
}
