<?php

namespace RoyalAcademyBundle\Repository;

/**
 * realizarExamenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class realizarExamenRepository extends \Doctrine\ORM\EntityRepository
{
}
